name: Check
on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: aarch64-linux-android
          profile: minimal
          override: true
          components: clippy, rustfmt
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r22

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/
            target/
          key: check-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-ndk

      - name: Check for clippy warnings
        uses: actions-rs/cargo@v1
        with:
          command: ndk
          args: clippy
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
